
[functions.justcall-call-handler]
enabled = true
verify_jwt = false
import_map = "./functions/v1/justcall-call-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/v1/justcall-call-handler/index.mjs"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/v1/justcall-call-handler/*.html" ]
